language: python

python:
    - "2.7"

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install nose"

script:
    - "nosetests --with-coverage --cover-package=pyspell qa/unittests/"

after_success:
    coveralls

notifications:
  email:
    on_success: never
    on_failure: always